"""Add acknowledged_change_version to fuel_orders

Revision ID: 0d7fed574dcc
Revises: 3b2a4825b8ca
Create Date: 2025-06-09 05:17:01.225662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7fed574dcc'
down_revision = '3b2a4825b8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged_change_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_change_version')

    # ### end Alembic commands ###
