"""Add waiver_source to receipt_line_items

Revision ID: 34bba6616d2a
Revises: 62aa550028fb
Create Date: 2025-07-10 21:28:01.646034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bba6616d2a'
down_revision = '62aa550028fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    waiver_source_enum = sa.Enum('AUTOMATIC', 'MANUAL', name='waiversource')
    waiver_source_enum.create(op.get_bind())
    
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiver_source', waiver_source_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.drop_column('waiver_source')
    
    # Drop the enum type
    waiver_source_enum = sa.Enum('AUTOMATIC', 'MANUAL', name='waiversource')
    waiver_source_enum.drop(op.get_bind())

    # ### end Alembic commands ###
