"""add_change_version_and_gallons_dispensed_to_fuel_orders

Revision ID: 3b2a4825b8ca
Revises: f0782657b0c2
Create Date: 2025-06-09 04:46:22.254383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2a4825b8ca'
down_revision = 'f0782657b0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('gallons_dispensed', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_fuel_order_id'), ['fuel_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_fuel_order_id'))

    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.drop_column('gallons_dispensed')
        batch_op.drop_column('change_version')

    # ### end Alembic commands ###
