"""Add resource_type and scope columns to permissions table

Revision ID: 5fd1137c554d
Revises: 3fc8569229ce
Create Date: 2025-06-06 05:24:20.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd1137c554d'
down_revision = '3fc8569229ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.String(length=20), nullable=False, server_default='any'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('scope')
        batch_op.drop_column('resource_type')
    # ### end Alembic commands ###
