"""Add fbo_location_id to User model for multi-tenancy

Revision ID: 63198927b432
Revises: b86dd54dc423
Create Date: 2025-06-10 01:51:53.515955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63198927b432'
down_revision = 'b86dd54dc423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fbo_location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_fbo_location_id'), ['fbo_location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_fbo_location_id'))
        batch_op.drop_column('fbo_location_id')

    # ### end Alembic commands ###
