"""align_fee_category_model_with_db

Revision ID: 6e43a849ef92
Revises: 2a16779244f6
Create Date: 2025-06-28 23:04:31.883150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e43a849ef92'
down_revision = '2a16779244f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fee_category_fbo_name', type_='unique')
        batch_op.create_unique_constraint('_fbo_classification_name_uc', ['fbo_location_id', 'name'])

    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_prices_fuel_type_id'), ['fuel_type_id'], unique=False)
        batch_op.create_unique_constraint('uq_fuel_price_fbo_fuel_date', ['fbo_location_id', 'fuel_type_id', 'effective_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fuel_price_fbo_fuel_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_fuel_prices_fuel_type_id'))

    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.drop_constraint('_fbo_classification_name_uc', type_='unique')
        batch_op.create_unique_constraint('uq_fee_category_fbo_name', ['fbo_location_id', 'name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
