"""add_details_to_customer_model

Revision ID: 7f975c9dedcf
Revises: d565f3f96234
Create Date: 2025-07-12 07:27:58.300642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f975c9dedcf'
down_revision = 'd565f3f96234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    payment_type_enum = sa.Enum('CREDIT_CARD_ON_FILE', 'NET_30_ACCOUNT', 'CASH_OR_CHECK', 'PREPAYMENT_REQUIRED', name='paymenttype')
    poc_role_enum = sa.Enum('OWNER', 'OPERATOR', 'PILOT', name='pocrole')
    payment_type_enum.create(op.get_bind())
    poc_role_enum.create(op.get_bind())

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_type', payment_type_enum, nullable=True))
        batch_op.add_column(sa.Column('poc_role', poc_role_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('poc_role')
        batch_op.drop_column('payment_type')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('company_name')

    # Drop the enum types that were created
    op.execute("DROP TYPE IF EXISTS paymenttype;")
    op.execute("DROP TYPE IF EXISTS pocrole;")
    # ### end Alembic commands ###
