"""Add priority field to fuel_orders table

Revision ID: 8490e1840410
Revises: 0d7fed574dcc
Create Date: 2025-06-09 23:12:31.629249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8490e1840410'
down_revision = '0d7fed574dcc'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type with the correct values that the model expects
    fuelorderpriority = postgresql.ENUM('NORMAL', 'HIGH', 'LOW', name='fuelorderpriority')
    fuelorderpriority.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'LOW', name='fuelorderpriority'), nullable=False, server_default='NORMAL'))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_completion_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.drop_column('estimated_completion_time')
        batch_op.drop_column('review_notes')
        batch_op.drop_column('priority')

    # Drop the enum type
    fuelorderpriority = postgresql.ENUM('NORMAL', 'HIGH', 'LOW', name='fuelorderpriority')
    fuelorderpriority.drop(op.get_bind())
    # ### end Alembic commands ###
