"""Add category column to permissions table

Revision ID: 931518a1009f
Revises: cd7344a46b7f
Create Date: 2025-05-25 04:41:10.212989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931518a1009f'
down_revision = 'cd7344a46b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
