"""Add unique constraint to fee_categories on fbo_location_id and name

Revision ID: a525066160e4
Revises: 0f50b0972808
Create Date: 2025-06-25 19:19:48.423954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a525066160e4'
down_revision = '0f50b0972808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_fee_categories_fbo_location_id_name', ['fbo_location_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fee_categories_fbo_location_id_name', type_='unique')

    # ### end Alembic commands ###
