"""Add FBOAircraftTypeConfig for FBO-specific aircraft settings

Revision ID: b86dd54dc423
Revises: 8490e1840410
Create Date: 2025-06-10 01:46:39.994014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86dd54dc423'
down_revision = '8490e1840410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbo_aircraft_type_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fbo_location_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=False),
    sa.Column('base_min_fuel_gallons_for_waiver', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fbo_location_id', 'aircraft_type_id', name='uq_fbo_aircraft_config')
    )
    with op.batch_alter_table('fbo_aircraft_type_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fbo_aircraft_type_configs_aircraft_type_id'), ['aircraft_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fbo_aircraft_type_configs_fbo_location_id'), ['fbo_location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fbo_aircraft_type_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fbo_aircraft_type_configs_fbo_location_id'))
        batch_op.drop_index(batch_op.f('ix_fbo_aircraft_type_configs_aircraft_type_id'))

    op.drop_table('fbo_aircraft_type_configs')
    # ### end Alembic commands ###
