"""add_display_name_to_permission_groups

Revision ID: b9f9fd5df01d
Revises: cfdd930e28a0
Create Date: 2025-06-03 06:13:31.214271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f9fd5df01d'
down_revision = 'cfdd930e28a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission_groups')
    op.drop_table('permission_group_permissions')
    with op.batch_alter_table('permission_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('permission_groups_parent_group_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('permission_groups_created_by_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'permission_groups', ['parent_id'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('created_by_migration')
        batch_op.drop_column('parent_group_id')
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('scope')
        batch_op.drop_column('is_active')
        batch_op.drop_column('action')
        batch_op.drop_column('requires_resource_context')
        batch_op.drop_column('is_system_permission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_permission', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requires_resource_context', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('permission_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_migration', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('permission_groups_created_by_user_id_fkey'), 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('permission_groups_parent_group_id_fkey'), 'permission_groups', ['parent_group_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('parent_id')
        batch_op.drop_column('display_name')

    op.create_table('permission_group_permissions',
    sa.Column('permission_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_groups.id'], name=op.f('permission_group_permissions_permission_group_id_fkey')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('permission_group_permissions_permission_id_fkey')),
    sa.PrimaryKeyConstraint('permission_group_id', 'permission_id', name=op.f('permission_group_permissions_pkey'))
    )
    op.create_table('user_permission_groups',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_groups.id'], name=op.f('user_permission_groups_permission_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_permission_groups_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'permission_group_id', name=op.f('user_permission_groups_pkey'))
    )
    # ### end Alembic commands ###
