"""Add LST specific fields to users table

Revision ID: d8897d7b926b
Revises: 931518a1009f
Create Date: 2025-05-25 12:39:12.796903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8897d7b926b'
down_revision = '931518a1009f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, default='active'))
        batch_op.add_column(sa.Column('shift', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('performance_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('orders_completed', sa.Integer(), nullable=True, default=0))
        batch_op.add_column(sa.Column('average_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hire_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_column('hire_date')
        batch_op.drop_column('last_active')
        batch_op.drop_column('average_time')
        batch_op.drop_column('orders_completed')
        batch_op.drop_column('performance_rating')
        batch_op.drop_column('certifications')
        batch_op.drop_column('shift')
        batch_op.drop_column('status')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
