"""Add fee_schedule_versions table

Revision ID: ef1248e9d102
Revises: 06442d69e349
Create Date: 2025-07-02 06:03:49.504067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1248e9d102'
down_revision = '06442d69e349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration_data', sa.JSON(), nullable=False),
    sa.Column('version_type', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_schedule_versions')
    # ### end Alembic commands ###
