"""Add FeeRuleOverride table

Revision ID: f8606116088a
Revises: 42323865a0dc
Create Date: 2025-06-20 04:25:11.122028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8606116088a'
down_revision = '42323865a0dc'
branch_labels = None
depends_on = None


def upgrade():
    """Add FeeRuleOverride table"""
    # Check if table already exists
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'fee_rule_overrides'
        );
    """))
    table_exists = result.scalar()
    
    if not table_exists:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('fee_rule_overrides',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fbo_location_id', sa.Integer(), nullable=False),
        sa.Column('aircraft_type_id', sa.Integer(), nullable=False),
        sa.Column('fee_rule_id', sa.Integer(), nullable=False),
        sa.Column('override_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('override_caa_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ),
        sa.ForeignKeyConstraint(['fee_rule_id'], ['fee_rules.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('fbo_location_id', 'aircraft_type_id', 'fee_rule_id', name='_fbo_aircraft_fee_rule_uc')
        )
        with op.batch_alter_table('fee_rule_overrides', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_fee_rule_overrides_fbo_location_id'), ['fbo_location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """Remove FeeRuleOverride table"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_rule_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rule_overrides_fbo_location_id'))

    op.drop_table('fee_rule_overrides')
    # ### end Alembic commands ###
